### ISSUE TITLE
Contaminants inspection analysis; bedtools Segmentation fault: 11

### ISSUE THREAD

**Issue by ieknot** [MaestSi/ONTrack#3]
Hi there,

I'm trying to run the code for the contaminants inspection analysis, and am running into a 'segmentation fault' error when I do.

````
SAMPLE_NAME=BC08
ANALYSIS_DIR=/path/to/BC08/files
PIPELINE_DIR=/path/to/ONTrack

source activate ONTrack_env

cd $ANALYSIS_DIR
$PIPELINE_DIR"/Calculate_mapping_rate.sh" $SAMPLE_NAME".fastq" $SAMPLE_NAME"/"$SAMPLE_NAME"_decont.fastq" $SAMPLE_NAME".contigs.fasta"

if [ ! -d "contaminants_analysis" ]; then
  mkdir contaminants_analysis
fi

samtools view -f4 -b $SAMPLE_NAME"_reads_on_contig.bam" > "contaminants_analysis/"$SAMPLE_NAME"_unmapped.bam"
bedtools bamtofastq -i "contaminants_analysis/"$SAMPLE_NAME"_unmapped.bam" -fq "contaminants_analysis/"$SAMPLE_NAME".fastq"
Segmentation fault: 11
````
I checked for the error online, and found amongst others [this thread](https://github.com/arq5x/bedtools2/issues/723). However, I checked the bedtools version, and since it's one of the latest versions I assume it's fine?
````
bedtools --version
bedtools v2.29.0
````
The folder is created, the bam file has information in it, but the fastq file is not 'filled', so to say:
<img width="625" alt="Screenshot 2019-12-17 at 23 15 30" src="https://user-images.githubusercontent.com/57810007/71042292-3aa9cd00-2123-11ea-98ce-4e1257f0d390.png">

My question: how do I solve this error? Is there any way to update the bedtools in the virtual environment? Thanks in advance!

**Comment by ieknot** [comment]
Oh, on a side note: it took me a while to realise that the `Calculate_mapping_rate.sh` script required the `MINICONDA_DIR` in front of `/envs/ONTrack_env/bin/minimap2` / `/envs/ONTrack_env/bin/samtools` to run Minimap2 and samtools. Maybe it's possible to highlight this in the readme?

**Comment by MaestSi** [comment]
Hi Ineke,
I don't think this is due to bedtools version. I was using bedtools v2.28.0, and I updated to bedtools v2.29.2, but still I don't get any errors while running the contaminants analysis code. You could try to run ```conda update bedtools```, after ```source activate ONTrack_env```, to update from v2.29.0 to v2.29.2, but I fear it is not going to solve the issue. At the moment I don't have a solution for this issue. If you don't mind, could you share with me BC08_unmapped.bam, so that I can further inspect? simone.maestri@hotmail.it is my e-mail address. Regarding your minor point, I now updated README and scripts ```Calculate_mapping_rate.sh```, ```Calculate_error_rate.sh``` and ```Sanger_check.sh```, so that the executable version found in the PATH is used, unless a different executable is specified. In this way, after activating ONTrack_env environment there is no need for modifying the scripts.

**Comment by MaestSi** [comment]
After testing bedtools v2.29.0 I was able to reproduce your error. So, updating bedtools should solve the issue. Let me know.
Simone

**Comment by ieknot** [comment]
Hi Simone, thanks for your quick reply. I updated bedtools as you described and it solved the problem! Thanks so much. And thanks for implementing the suggestion.

**Comment by MaestSi** [comment]
I'm glad it now works!
Bye,
Simone
