### ISSUE TITLE
Long run time 

### ISSUE THREAD

**Issue by Cynthiavlu** [MaestSi/ONTrack#6]
Hi,

I've been trying to use ONTrack for my analysis. 
I have extracted DNA from a mock community and used MinION sequencing. 
First, i was only using one barcode so i could test wether ONTrack is suitable for us. 
I used MetatONTrack.sh and at first i received an blast database error saying not valid version 4 database. 
I think is solved that one by updating Blast to version 2.10.1

Now when I start running Ontrack with one barcode (3.5 gigabyte) it looks like it is doing something, however after 8 hours it is still te same. When i cancel the command i only have a BC01_top_Blast_hits_tmp.txt file but nothing else. 
Is it normal that ONTrack takes this amount of time for only one barcode? 

Kind regards

**Comment by MaestSi** [comment]
Hi,
the Blast database issue you received is probably due to too old Blast version compared to the downloaded database, as you already noticed.
If I understand correctly, you succeeded running MetatONTrack.sh, and now you have a folder where the file you provided as an input (a single barcode) was split in many BC*.fast* files, according to each reads' top hit.
In my experience, the first clustering step performed by VSEARCH is the most time consuming one, because it tries to cluster all reads. However, if you used MetatONTrack.sh before, you can assume all reads in each file belong to the same species, therefore you may disable the preliminary clustering step, as suggested in the README. Did you already do this? At which step is the pipeline possibly stuck?
Simone

**Comment by MaestSi** [comment]
Please, confirm I understood correctly that reads from the single barcode you tested are generated from a mixed sample (namely that the mock community is composed of multiple species). In case you are mainly interested in performing taxonomy assignment and consensus sequence calling is not your main aim, you may also want to check out [MetONTIIME](https://github.com/MaestSi/MetONTIIME) and [MetaBlast](https://github.com/MaestSi/MetaBlast). 
Simone

**Comment by Cynthiavlu** [comment]
Hi, i did not receive a folder with split files. i only received BC01_top_Blast_hits_tmp.txt. 
It was indeed a barcode with a mixed sample. We do need the consensus sequence as an output. 
I do think that the determination of a consensus sequence is necessary in order to polish, i understand from your reply that the different consensus sequences cannot be determined from a mixed sample, is that correct? 
If we use you suggestion of using MetONTIIME or MetaBlast with our 16s ONT data, is there polishing involved?

**Comment by MaestSi** [comment]
If *MetatONTrack.sh* was successfull, you should get **MetatONTrack_output** folder, containing reads split by candidate species. In case you don't have that folder, you probably still have some issues with the configuration. For example, how did you set the Blast database in the script?
Different consensus sequences from a mixed sample can only be obtained if you manage to split reads belonging to different organisms into different files, and *MetatONTrack.sh* is a script attempting to do that using an external database. De-novo methods for doing this (no external database involved) don't work very well for Nanopore data, especially if you have many similar species in your sample. You may only do that successfully if you have few different species with high divergence in your sample (for example in case you meant to amplify CO1 from one insect and accidentally you also amplified CO1 from a parasite).
After splitting reads from different species to different files, you can run *ONTrack.R* on each file, which will then hopefully contain only reads from a single species.
MetONTIIME and MetaBlast do not perform any polishing or consensus sequence generation, since their aim is just to tell you what is the composition of your sample, by comparing reads to a database.
Simone

**Comment by MaestSi** [comment]
Hi, are there any news on this? Have you been able to solve the issue?
Simone

**Comment by Cynthiavlu** [comment]
Hi, 
apologies for the late respons. 
I haven't been able to try it again. 
I'll try again tomorrow and will let you know!

**Comment by MaestSi** [comment]
Hi, I'll close the issue for now. Fell free to reopen it if you try again and still face some issues!
Simone

**Comment by Cynthiavlu** [comment]
Hi 
Sorry for the late reply. I started the pipeline on may 6th around 5:15pm. 
I just checked and it is still running meaning it is running now for 4 days and 17 hours.
The only file  I see is "BC01_top_Blast_hits_tmp.txt"

In the MetatONTrack.sh script the database is set like this. 

#######################
THREADS=8
DB=/home/cynthia/NCBI_nt_db/nt                                         #e.g. PRJNA33175 BioProject for Bacterial 16S

Can you tell me if this is correct.

**Comment by MaestSi** [comment]
Hi,
yes, the DB line is ok. Is the file being written? 

You could try with:

`cat BC01_top_Blast_hits_tmp.txt | cut -f1 | sort | uniq | wc -l
`

and compare it with the output of:

`cat BC01.fasta | grep "^>" | wc -l`

to see how many sequences have already been Blasted out of the full dataset.
Best,
Simone

**Comment by Cynthiavlu** [comment]
With the first command it showed: 56267 and the second 1145695. 
As far as i can see it is still running. is is running little to a week now. 
Is that normal?

**Comment by MaestSi** [comment]
It looks like it has analysed just 5% of your reads, so it would take about 5 months to complete! That is normal, because you are Blasting a huge amount of reads to a very big database. For a preliminary test I would suggest picking 5k reads and see how it looks like, or using a marker gene-specific database.
Simone

**Comment by Cynthiavlu** [comment]
That made so much sense. 
I changed the database to the 16s database and now it was finished in two days. 
Now i do have the folders. In the )logs folder i have a lot of files including BC00. Can you maybe tell me what these files are? 
Thank you for your help!

**Comment by MaestSi** [comment]
Hi,
in the MetatONTrack_output_logs folder you should have some text files with BC<num>_<top_hit_species_name>_reads_IDs.txt, where each file contains the IDs of reads assigned to the <top_hit_species_name> species, and files \*Blast\*\_counts.txt, describing the number of reads supporting each taxa. Based on this you should be able to identify species of interest (they may be all of interest for you) and use the BC\<id\> - \<species_name\> couple as a key for selecting fastq and fasta files of interest in MetatONTrack_output folder. After you have removed species that are not interesting for you, you could run **ONTrack.R** using MetatONTrack_output folder as the working directory. Reads in each file are used for producing a consensus sequence, that is finally Blasted to NCBI nt db. Is it clearer now?
Simone
